### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by chmac** [tg44/heptapod#10]
This looks like exactly what I was thinking to write (although I figured I'd test out rust). Thanks for sharing it.

I really appreciate the simplicity and the fact that I can dry run to see what's going to happen. Hopefully the GitHub star count rises and folks start to see this as a viable alternative to asimov and the seemingly abandoned tmignore.

**Comment by tg44** [comment]
If you are interested, PRs are welcome. I'm not a big go dev, this is my first project in it, any contrib and advice welcomed.

**Comment by chmac** [comment]
Same here, I wrote one simple project in go, I work mostly in TypeScript these days. My go skills are really non existent!

I have now installed so will try some experiments and report any issues / suggestions. 👍🏼

**Comment by tg44** [comment]
Thank you for the thank you, I will close this now as a cleanup :)
