### ISSUE TITLE
Enabling / disabling rules reformats them

### ISSUE THREAD

**Issue by chmac** [tg44/heptapod#11]
The default rules seem to have different formatting from the output generated by the command.

So running:

```
heptapod rules disable node
heptapod rules enable node
```

Results in a different file. I started tracking my `~/.heptapod` folder in git so I can sync it between machines.

As per #10 though, thanks again, this is really exactly the type of app I wanted for this purpose. Simple, does its job, easy to understand config, amazing!

**Comment by tg44** [comment]
I close this one as a "not as easy to fix as it should", if this gets a showstopper for others, I will probably reconsider it later.

**Comment by chmac** [comment]
@tg44 Totally understand, we've done the same on several open source projects. One thing we found useful, ymmv, was to tag issues that we closed but would be open to resolving but don't have the current time, etc. I think we tagged them as "not-planned" to distinguish them from closed and invalid, etc.
