### ISSUE TITLE
Feature Request: Add hostname to log file or name

### ISSUE THREAD

**Issue by chmac** [tg44/heptapod#13]
As I'm tracking `~/.heptapod` in git and syncing it between machines, I realise that I won't know which log files were generated on which machines. Any chance you'd be open to adding the hostname either in the filename or as part of the log file?

For example, maybe `~/.heptapod/logs/${host}_${time}.log` could work?

Using `hostname -s` seems to print out just the name without the domain part, which would be perfect in my opinion.

**Comment by amoghrajesh** [comment]
@chmac is this issue still open? I would like to take it up for Hacktoberfest 2022.

**Comment by tg44** [comment]
I think it is still open and rather easy to implement as; https://github.com/tg44/heptapod/blob/main/pkg/tmutil/tmutil.go#L28 states the file name, pls if you are working on this check if we read/write that file name format anywhere else!

**Comment by chmac** [comment]
> @chmac is this issue still open? I would like to take it up for Hacktoberfest 2022.

To the best of my knowledge this feature request is still open. I'd be happy to help testing and so on if that's helpful.

**Comment by amoghrajesh** [comment]
Thank you for the clarification, @tg44, @chmac 
I will work on this issue

**Comment by amoghrajesh** [comment]
@tg44 @chmac is the machine that currently is storing the log file stored in any config?

**Comment by tg44** [comment]
Nope. You should get it from the runner computer.

**Comment by amoghrajesh** [comment]
@tg44 @chmac raised a PR for this change: https://github.com/tg44/heptapod/pull/16
Kindly help in reviews
