### ISSUE TITLE
Bug:" Error (-50) while attempting to change exclusion setting " while running heptapod run

### ISSUE THREAD

**Issue by jgoldhammer** [tg44/heptapod#14]
Running command

`heptpod run`

leads to following error:
`
Error (-50) while attempting to change exclusion setting.
`

![image](https://user-images.githubusercontent.com/3872101/165626340-c59062f3-2fcf-4c0d-87da-effe01025218.png)

Is it a problem with heptapod or with my machine?

Hint: I cannot print the logfile as it contains sensitive data from my employeers projects. The log file lists a lot of directories to exclude, but no further error.

**Comment by jgoldhammer** [comment]
I have excluded the path now and it works again...

![image](https://user-images.githubusercontent.com/3872101/165629051-ea7ed20b-3e9d-4745-8e8e-610fdfa6ca3c.png)

**Comment by tg44** [comment]
with the given #path# can you check:
```bash
tmutil isexcluded #path#
tmutil addexclusion #path#
```
the first line should return true if the path is already excluded, and the second command should exclude it if it is not. 

In theory, the second command should fail the same way as heptapod failed if the first command says that it is not excluded from tm.

If the first command says it is excluded that would be really strange bcs that means that we tried to exclude it, and we failed, but we didn't failed :D

**Comment by tg44** [comment]
Googling the bug; https://discussions.apple.com/thread/250603815

They said that you probably have some permission issues. Can you also "ls -la" that folder and copy the permissions for me?

**Comment by sfleiter** [comment]
I faced the same issues when it comes to missing permissions.

I suggest to improve handling of the situation
1. better error message telling about permissions
2. run sudo tmutil for the user in such cases so that only tmutil runs under sudo and not the whole program (if easily possible)

**Comment by sfleiter** [comment]
Running commands with sudo seems relatively easy, if there is interest in this I might give it a go when I find some time.
Of course this only works for interactive runs of heptapod.

**Comment by matgessel** [comment]
Not using heptapod, but I thought I'd share another reproduction case in case it comes up. I got **Error (-50)** when trying to exclude `/private/var/folders/`. The workaround was to add the -p path flag. I'm guessing that SIP disallows changing the attributes of that folder.

Fails:  `sudo tmutil addexclusion /private/var/folders/`
Works: `sudo tmutil addexclusion -p /private/var/folders/`

If heptapod always uses "-p" for paths, then you should never run into this case.
