### ISSUE TITLE
add brew service (like asimov)

### ISSUE THREAD

**Issue by PhilippMolitor** [tg44/heptapod#25]
Asimov provides a neat `brew service` definition for macOS' launch agent, so it periodically runs in the background:
https://github.com/stevegrunwell/asimov/blob/develop/com.stevegrunwell.asimov.plist

Heptapod should do the same :)

**Comment by PhilippMolitor** [comment]
I just googled a bit about those LaunchAgent Plist definitions, i imagine the config for heptapod looking something like this:
```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.tg44.heptapod</string>
        <key>Program</key>
        <string>/opt/homebrew/bin/heptapod</string>
        <key>ProgramArguments</key>
        <array>
            <string>run</string>
        </array>
        <key>StartInterval</key>
        <!-- 1 hour = 60 * 60 -->
        <integer>3600</integer>
    </dict>
</plist>
```

see: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

**Comment by tg44** [comment]
Yes. This was on my todo list. Can you test it, and PR it?

**Comment by PhilippMolitor** [comment]
I had a look as asimov's implementation. 

First, they have an `install.sh` script that does the following: (edited & simplified to match the example above):
```bash
DIR="$(cd "$(dirname "$0")" || return; pwd -P)" # current directory
PLIST="com.stevegrunwell.asimov.plist" # filename of .plist

if launchctl list | grep -q com.tg44.heptapod; then
    echo -e "\\nlaunchctl: unloading existing ${PLIST}";
    launchctl unload "${DIR}/${PLIST}"
fi

launchctl load "${DIR}/${PLIST}" && echo -e "\\nlaunchctl: loaded plist ${PLIST}";
```

Then there is this part in the [brew formula](https://github.com/Homebrew/homebrew-core/blob/ab1fba6eee543edf00cb7003385d7ec8257371de/Formula/a/asimov.rb):
```rb
service do
  run opt_bin/"asimov"
  run_type :interval
  require_root true
  interval 86400 # 24 hours = 60 * 60 * 24
end
```
(asimov symlinks itself to `/opt/bin`, maybe hepatpod should do this as well for the sake of cleanness)

I am unfortunately not really sure how `brew service` works, especially related to the launchctl plist file, so I am not of much help for that right now. 
One other thing I had in mind: When installing via the homebrew formula, it could run an `install.sh` script just like asimov probably does. This could also include copying the rule templates to the user's directory, so the initially installed version is ready out of the box, kinda like a "batteries included" approach.
