### ISSUE TITLE
Warning from Homebrew

### ISSUE THREAD

**Issue by GBrachetta** [tg44/heptapod#4]
When installing on my Mac I got this:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tg44/heptapod tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/tg44/homebrew-heptapod/heptapod.rb:10
```

So I wanted to report it to you in case you need to fix it.

Edit: I think `goreleaser` fixed this in version [v0.183.0 ](https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0)- I think Homebrew deprecated the use of `bottle :unneeded` after you published your latest version of heptapod, so I guess it will be automatically fixed in your next release if you update `goreleaser`

**Comment by tg44** [comment]
Thx the heads up! I will update a lot of things after the holidays, stay tuned :)

**Comment by GBrachetta** [comment]
Can't wait!

**Comment by tg44** [comment]
Is this still appear?

**Comment by GBrachetta** [comment]
No, that one was already gone in your previous pushed version, so feel free to close this one! 😊
